module.exports = {
	Help: require('./help'),
	Shop: require('./shop'),
	Item: require('./item'),
	Buy: require('./buy'),
	Sell: require('./sell'),
	Use: require('./use'),
	Duel: require('./duel'),
	Equip: require('./equip'),
	Open: require('./open'),
	Trade: require('./trade'),
	Character: require('./character'),
	Class: require('./class'),
	Vote: require('./vote'),
	Hourly: require('./hourly'),
	Daily: require('./daily'),
	Leaderboard: require('./leaderboard'),
	Gamble: require('./gamble'),
	Invite: require('./invite'),
	Changelog: require('./changelog'),
	Stats: require('./stats'),
	Add: require('./add'),
	Edituser: require('./edituser'),
	Prefix: require('./prefix'),
	Reload: require('./reload'),
	Test: require('./test'),
	Update: require('./update'),
};
