module.exports = {
	Help: require('./help'),
	Item: require('./item'),
	Shop: require('./shop'),
	Buy: require('./buy'),
	Sell: require('./sell'),
	Profile: require('./profile'),
	Class: require('./class'),
	Quest: require('./quest'),
	Vote: require('./vote'),
	Hourly: require('./hourly'),
	Daily: require('./daily'),
	Weekly: require('./weekly'),
	Leaderboard: require('./leaderboard'),
	Invite: require('./invite'),
	Add: require('./add'),
	Prefix: require('./prefix'),
	Reload: require('./reload'),
};
